input {
  file {
    path => "/usr/share/logstash/logs/*.log"  # Ensure this path is correct
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }

  # Cowrie JSON logs
  file {
    path => "/usr/share/logstash/cowrie/var/log/cowrie/cowrie.json"  # Path to Cowrie log
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  # HTTP logs
  if [path] =~ "http.log" {
    json { source => "message" }
    date { match => ["timestamp", "ISO8601"] }
  }

  # RTSP logs
  else if [path] =~ "rtsp.log" {
    grok { match => { "message" => "%{IP:source_ip}:%{NUMBER:port} - %{GREEDYDATA:data}" } }
    mutate { add_field => { "protocol" => "RTSP" } }
    date { match => ["timestamp", "ISO8601"] }
  }

  # ONVIF logs
  else if [path] =~ "onvif.log" {
    json { source => "message" }
    date { match => ["timestamp", "ISO8601"] }
  }

  # ICMP logs
  else if [path] =~ "icmp.log" {
    json { source => "message" }
    date { match => ["timestamp", "ISO8601"] }
  }

  # Cowrie logs
  else if [path] =~ "cowrie.json" {
    date { match => ["timestamp", "ISO8601"] target => "@timestamp" }
    mutate {
      add_field => { "protocol" => "SSH-Honeypot" }
      add_field => { "log_type" => "cowrie" }
    }
  }

  # Mutate to add general log type based on file path
  mutate {
    add_field => { "log_type" => "%{path}" }
  }
}

output {
  # Output to console for debugging
  stdout { codec => rubydebug }

  # Output to Elasticsearch
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
